name: tharad_tech
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  build_runner: ^2.10.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  logger: ^2.6.2
  lottie: 3.3.1
  pinput: ^5.0.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  retrofit_generator: ^10.0.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#F4F7F6" # Color of the background of the splash screen
  image: assets/images/splash_screen.png # image path
  android_12:
    image: assets/images/splash_screen.png # image path
    color: "#F4F7F6" # Color of the background of the splash screen

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/tajawal/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
