name: tharad_tech
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  animate_do: ^4.2.0
  lottie: ^3.3.1
  shimmer: ^3.0.0

  dio: ^5.7.0
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.4.0

  flutter_bloc: ^9.1.0
  get_it: ^7.7.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.20.2

  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  pinput: ^5.0.0
  device_preview: ^1.2.0
  flutter_localization: ^0.3.2
  logger: ^2.3.0

  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#F4F7F6"
  image: assets/images/splash_screen.png
  android_12:
    image: assets/images/splash_screen.png
    color: "#F4F7F6"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/tajawal/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
